on:
  push:
    branches:
      - production

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    name: Code Inspector Check
    steps:
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

