on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Code Inspector Check
    steps:
    - uses: actions/checkout@v2

    # Sets up python
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
      run: |
        # Upgrade pip
        python3 -m pip install --upgrade pip
        # Install build deps
        python3 -m pip install setuptools wheel twine
        # If requirements.txt exists, install from it
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Tests with unittest
    - name: Test with unittest
      run: |
        PYTHONPATH=. python3 -m unittest discover

    # Tests with unittest
    - name: Install
      run: |
        python3 setup.py install

    - name: Publish a Python distribution to PyPI
      if: ${{ github.ref == 'refs/heads/production' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}


